---
- name: Создание сети
  community.docker.docker_network:
    name: "{{ network_name }}"
    driver: overlay

- name: Выкладка сервисов
#  import_tasks
  include_tasks: "../services/{{ item.name }}/service.yml"
  vars:
    - name: "{{ item.name }}"
    - version: "{{ item.version }}"
# services находится в vars задачи
  loop: "{{ services }}"
