version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rmq_net

  rmq-test:
    build: ./
    container_name: 'rmq-test'
    networks:
      - rmq_net
networks:
  rmq_net:
    driver: bridge