---
- name: Ping test
#  hosts: manager
  hosts: all
  tasks:
    - name: Ping host
      ping:

#    - name: Display ansible_facts
#      debug:
#        var: "ansible_facts"

    - name: Display ansible_facts default_ipv4
      debug:
        var: "ansible_facts.default_ipv4"

    - name: Display ansible_facts.distribution_version
      debug:
        var: "ansible_facts.distribution_version"
    - name: Display ubuntu_release
      debug:
        var: "ubuntu_release"

    - name: Display ansible_facts.distribution_release
      debug:
        var: "ansible_facts.distribution_release"
    - name: Display ansible_distribution_release
      debug:
        var: "ansible_distribution_release"

    - name: Display all_ipv4_addresses
      debug:
        var: "ansible_facts.all_ipv4_addresses"

    - name: Display interfaces
      debug:
        var: "ansible_facts.interfaces"



#    - name: Copy value of var1 to var2
#      set_fact:
#        ansible_distribution_release: "{{ ansible_facts.distribution_release }}"




    - name: Display all
      debug:
        msg: "processor_count : {{ ansible_facts.processor_count }} processor_cores: {{ ansible_facts.processor_cores }} processor_vcpus:{{ ansible_facts.processor_vcpus }}"


