# compose-file
version: '3.4'
services:
  php-fpm:
    image: php-fpm:latest
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 1s
        order: start-first
      restart_policy:
        condition: on-failure
      resources:
        reservations:
          cpus: '0.5'