---
- hosts: worker
  tasks:
    - name: Display token_manager
      debug:
        var: "hostvars['master']['ansible_facts']['token_worker']"
    - name: Display  ansible_facts.eth1.ipv4.address
      debug:
        msg: "{{ ansible_facts.eth1.ipv4.address }}"
    - name: Display  ansible_facts.eth1.ipv4.address
      debug:
        var: "hostvars['master']['ansible_facts']['master_ip4_beget_private_network']"

    - name: Подключение
      community.docker.docker_swarm:
        state: join
        remote_addrs: "{{ hostvars['master']['ansible_facts']['master_ip4_beget_private_network'] }}"
        join_token: "{{ hostvars['master']['ansible_facts']['token_worker'] }}"
