---
- hosts: manager
#  roles:
#    - swarm_init
  tasks:
#    - name: print
#      debug:
#         var: token
#    - name: token_manager
#      debug:
#          var: token_manager
    - name: msg hostvars['master'] token_worker
      debug:
        msg: "{{hostvars['master']['ansible_facts']['token_worker']}}"
