---
- name: Swarm show
  #  собирает факты на master и получает ip
  hosts: manager
  gather_facts: true
#  gather_facts: no
  tasks:
    - name: Display token_manager
      debug:
        var: "hostvars['master']['ansible_facts']['token_worker']"
