---
# ansible-playbook -i inventory test-docker-secret.yml --vault-password-file ~/gayrat/.pass
# секреты можно создавать только для docker swarm manager модуля
- hosts: manager
  gather_facts: no
  roles:
    - role: secret-test2

