---
- hosts: manager
  vars:
    git_repository_name: "rmq-test"
    git_repository_destination_dir: "{{ git_repository_base_dir }}{{ git_repository_name  }}"
    git_repository_branch: RMQ-test
    git_repository_version: latest
    git_repository_url: "https://github.com/gayratv/docker-swarm-ansible"
  roles:
    - role: git-clone
    - role: docker-build

