---
- name: "[{{ name }}] Выкладка сервиса"
  block:
    - name: "[{{ name }}] Выкладываем сервис"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        image: "{{ registry_name }}{{ name }}:{{ version }}"
        state: present
        force_update: true
        networks:
          - name: "{{ network_name }}"
        publish:
          - mode: ingress
            protocol: tcp
            published_port: 3000
            target_port: 3000
        placement:
#          preferences:
#            - spread: node.labels.mylabel
#          constraints:
#            - node.role == manager
#            - engine.labels.operatingsystem == ubuntu 14.04
          replicas_max_per_node: 1
        replicas: 3
        env:
          PORT_PARAM: "8000"
  tags: "{{ name }}"
