---
- name: Подключение
  community.docker.docker_swarm:
    state: join
    remote_addrs: "{{ hostvars['master']['ansible_facts']['default_ipv4']['address'] }}"
#    join_token: "{{ hostvars['master']['ansible_facts']['token_worker'] }}"
    join_token: >
      {{
        hostvars['master']['ansible_facts']['token_worker']
        if type == 'worker' else
        hostvars['master']['ansible_facts']['token_manager']
      }}
