---
- name: Подключение
  community.docker.docker_swarm:
    state: join
    remote_addrs: "{{ hostvars['master']['ansible_facts']['master_ip4_beget_private_network'] }}"
    join_token: >
      {{
        hostvars['master']['ansible_facts']['token_worker']
        if type == 'worker' else
        hostvars['master']['ansible_facts']['token_manager']
      }}
