---
# tasks file for roles/git-clone
- name: "Create dir {{ git_repository_base_dir }}"
  file:
    path: "{{ git_repository_base_dir }}"
    state: directory
  become: true
#  and the destination directory must be empty.
- name: Delete target directory if it exists "{{ git_repository_destination_dir }}"
  file:
    path: "{{ git_repository_destination_dir }}"
    state: absent
#      ignore_errors:
  become: true
- name: Create target directory "{{ git_repository_destination_dir }}"
  file:
    path: "{{ git_repository_destination_dir }}"
    owner: docker
    state: directory
  become: true
- name: "Clone Git repository {{ git_repository_name }}"
  ansible.builtin.git:
    repo: "{{ git_repository_url }}"
    dest: "{{ git_repository_destination_dir }}"
    single_branch: yes
    version: "{{ git_repository_branch }}"
    force: true
#    key_file: "~/.ssh/github/id_rsa"
#    Options git will pass to ssh when used as protoco
#    ssh_opts: "-o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"