---
- name: "[{{ name }}] Выкладка сервиса"
  block:
    - name: "[{{ name }}] Выкладываем сервис"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        image: "containous/whoami"
        state: present
        force_update: true
#  Time to wait before force killing a container.
#  Accepts a duration as a string in a format that look like: 5h34m56s, 1m30s etc. The supported units are us, ms, s, m and h.
        stop_grace_period: 1m
        networks:
          - name: "{{ network_name }}"
        publish:
          - mode: ingress
            protocol: tcp
            published_port: 8000
            target_port: 80
        placement:
        #          preferences:
        #            - spread: node.labels.mylabel
          constraints:
            node.role == manager
        #            - engine.labels.operatingsystem == ubuntu 14.04
        replicas: 1
  tags: "{{ name }}"
