---
# vars file for roles/docker-build2

git_repos:
  - git_def:
      git_repository_name: "rmq-test"
      git_repository_branch: RMQ-test
      git_repository_version: latest
      git_repository_url: "https://github.com/gayratv/docker-swarm-ansible"
  - git_def:
      git_repository_name: "ip-show"
      git_repository_branch: Docker_demo_3_IP
      git_repository_version: latest
      git_repository_url: "https://github.com/gayratv/docker-swarm-ansible"

#      - git_repository_destination_dir: "{{ git_repository_base_dir }}{{ git_repository_name  }}"
