---
# tasks file for roles/docker-registry-install
- name: Create Docker Registry
  community.general.docker_container:
    name: registry
    image: registry:latest
    state: started
    restart_policy: unless-stopped
    volumes:
      - /etc/docker/registry:/var/lib/registry
    published_ports:
      - "{{registry_port}}:5000"