---
#- name: Clear cached facts
#  ansible_cache_plugin:
#    clear: true
- name: advertise_addr_var
  debug:
    msg: "{{ advertise_addr }}"
- name: Инициализация swarm
  community.docker.docker_swarm:
    state: present
#    для timeweb - определили в VARs - файл vars/main.yml
  register: token

- name: Сохранение токенов
  set_fact:
    token_manager: "{{ token.swarm_facts.JoinTokens.Manager }}"
    token_worker: "{{ token.swarm_facts.JoinTokens.Worker }}"
    master_ip4_beget_private_network:  "{{ advertise_addr }}"
    cacheable: true
    ansible_fact_caching: true

